version: "3.8"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8008:8008"
    environment:
      - PYTHONUNBUFFERED=1
